services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      DB_HOST: 113.198.229.155
      DB_PORT: 359
      DB_USERNAME: runner
      DB_PASSWORD: 12341234
      DB_DATABASE: run
#    depends_on:
#      - mariadb

#  mariadb:
#    image: mariadb:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: 12341234
#      MYSQL_DATABASE: run
#      MYSQL_USER: runnershigh
#      MYSQL_PASSWORD: 12341234
#    ports:
#      - "1041:3306"
#    volumes:
#      - mariadb_data:/var/lib/mysql
#      - ./mariadb-init:/docker-entrypoint-initdb.d
#    command: —default-authentication-plugin=mysql_native_password
#
# volumes:
#  mariadb_data:
